### ISSUE TITLE
Testing when data servers are down

### ISSUE THREAD

**Issue by rstoneback** [rstoneback/pysat#133] opened 2019-01-02 17:08 UTC
From time to time data servers are down and this can cause tests to fail. For minor delays this is fine, however, extended issues can create the appearance that there are issues with pull requests. Take a look at test_instruments and see what changes can be made to help improve the situation.

Potential downside, allowing issues to pass without raising a Warning can allow some bugs to go undetected in instrument support functions. This could potentially be solved by decreasing the general verbosity of the testing log while increasing the feedback from the instrument support functions.

**Comment by rstoneback** [comment] 2019-01-02 17:13
See pull #132 where this issue is raised.

**Comment by rstoneback** [comment] 2019-01-02 17:13
Also present in testing logs of pull #128

**Comment by jklenzing** [comment] 2019-04-26 01:10
I propose that we close this issue.  While there are genuine periodic "server down" issues (such as supermag), we have had two major issues that we have caught (travis changing ftp, documented in #143 and #147, and lisard changing the data directory, documented in #213) which were initially thought to be "server down" issues.

I think the right solution is to independently verify servers are down, wait a few hours, then restart tests.  My concern is that if we skip the download tests (even if the test results are written out in the enormous log files), we can miss genuine problems caused by changes in the external data ecosystem.

**Comment by jklenzing** [comment] 2019-06-04 07:47
Closing after conversation with Russell.

**Closed by jklenzing** 2019-06-04 07:47 UTC
Labels: testing
